// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-9wWgk-HsYf3EpIa2dDCrlOLgUOlgwg',
    appId: '1:582699643243:web:5cf6e9b2c463622f6b9c2e',
    messagingSenderId: '582699643243',
    projectId: 'my-first-firebase-projec-a8057',
    authDomain: 'my-first-firebase-projec-a8057.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-a8057.appspot.com',
    measurementId: 'G-T26S24F73C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOg5kNKkdTvUbImc9lamBT6X_fxwEtww',
    appId: '1:582699643243:android:d3a1649aed141d226b9c2e',
    messagingSenderId: '582699643243',
    projectId: 'my-first-firebase-projec-a8057',
    storageBucket: 'my-first-firebase-projec-a8057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJc-Sf1Ck9y_j_CTdOLrUQTidOYTFLIWg',
    appId: '1:582699643243:ios:8cd11344258d6c106b9c2e',
    messagingSenderId: '582699643243',
    projectId: 'my-first-firebase-projec-a8057',
    storageBucket: 'my-first-firebase-projec-a8057.appspot.com',
    iosBundleId: 'com.example.meesho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJc-Sf1Ck9y_j_CTdOLrUQTidOYTFLIWg',
    appId: '1:582699643243:ios:8cd11344258d6c106b9c2e',
    messagingSenderId: '582699643243',
    projectId: 'my-first-firebase-projec-a8057',
    storageBucket: 'my-first-firebase-projec-a8057.appspot.com',
    iosBundleId: 'com.example.meesho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIjJV0K3qU8VS2dajyOUhy_nQpTGKgdho',
    appId: '1:582699643243:web:73218fe0c6c0439b6b9c2e',
    messagingSenderId: '582699643243',
    projectId: 'my-first-firebase-projec-a8057',
    authDomain: 'my-first-firebase-projec-a8057.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-a8057.appspot.com',
    measurementId: 'G-72135NY710',
  );
}
